<?php

namespace Database\Seeders;

use App\Models\Nationality;
use Illuminate\Database\Seeder;

class NationalitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $list = [
            0 => [
                'code' => 'AF',
                'country_en' => ' Afghanistan',
                'country_ar' => 'أفغانستان',
                'nationality_en' => 'Afghan',
                'nationality_ar' => 'أفغانستاني',
            ],
            1 => [
                'code' => 'AL',
                'country_en' => ' Albania',
                'country_ar' => 'ألبانيا',
                'nationality_en' => 'Albanian',
                'nationality_ar' => 'ألباني',
            ],
            2 => [
                'code' => 'AX',
                'country_en' => ' Aland Islands',
                'country_ar' => 'جزر آلاند',
                'nationality_en' => 'Aland Islander',
                'nationality_ar' => 'آلاندي',
            ],
            3 => [
                'code' => 'DZ',
                'country_en' => ' Algeria',
                'country_ar' => 'الجزائر',
                'nationality_en' => 'Algerian',
                'nationality_ar' => 'جزائري',
            ],
            4 => [
                'code' => 'AS',
                'country_en' => ' American Samoa',
                'country_ar' => 'ساموا-الأمريكي',
                'nationality_en' => 'American Samoan',
                'nationality_ar' => 'أمريكي سامواني',
            ],
            5 => [
                'code' => 'AD',
                'country_en' => ' Andorra',
                'country_ar' => 'أندورا',
                'nationality_en' => 'Andorran',
                'nationality_ar' => 'أندوري',
            ],
            6 => [
                'code' => 'AO',
                'country_en' => ' Angola',
                'country_ar' => 'أنغولا',
                'nationality_en' => 'Angolan',
                'nationality_ar' => 'أنقولي',
            ],
            7 => [
                'code' => 'AI',
                'country_en' => ' Anguilla',
                'country_ar' => 'أنغويلا',
                'nationality_en' => 'Anguillan',
                'nationality_ar' => 'أنغويلي',
            ],
            8 => [
                'code' => 'AQ',
                'country_en' => ' Antarctica',
                'country_ar' => 'أنتاركتيكا',
                'nationality_en' => 'Antarctican',
                'nationality_ar' => 'أنتاركتيكي',
            ],
            9 => [
                'code' => 'AG',
                'country_en' => ' Antigua and Barbuda',
                'country_ar' => 'أنتيغوا وبربودا',
                'nationality_en' => 'Antiguan',
                'nationality_ar' => 'بربودي',
            ],
            10 => [
                'code' => 'AR',
                'country_en' => ' Argentina',
                'country_ar' => 'الأرجنتين',
                'nationality_en' => 'Argentinian',
                'nationality_ar' => 'أرجنتيني',
            ],
            11 => [
                'code' => 'AM',
                'country_en' => ' Armenia',
                'country_ar' => 'أرمينيا',
                'nationality_en' => 'Armenian',
                'nationality_ar' => 'أرميني',
            ],
            12 => [
                'code' => 'AW',
                'country_en' => ' Aruba',
                'country_ar' => 'أروبه',
                'nationality_en' => 'Aruban',
                'nationality_ar' => 'أوروبهيني',
            ],
            13 => [
                'code' => 'AU',
                'country_en' => ' Australia',
                'country_ar' => 'أستراليا',
                'nationality_en' => 'Australian',
                'nationality_ar' => 'أسترالي',
            ],
            14 => [
                'code' => 'AT',
                'country_en' => ' Austria',
                'country_ar' => 'النمسا',
                'nationality_en' => 'Austrian',
                'nationality_ar' => 'نمساوي',
            ],
            15 => [
                'code' => 'AZ',
                'country_en' => ' Azerbaijan',
                'country_ar' => 'أذربيجان',
                'nationality_en' => 'Azerbaijani',
                'nationality_ar' => 'أذربيجاني',
            ],
            16 => [
                'code' => 'BS',
                'country_en' => ' Bahamas',
                'country_ar' => 'الباهاماس',
                'nationality_en' => 'Bahamian',
                'nationality_ar' => 'باهاميسي',
            ],
            17 => [
                'code' => 'BH',
                'country_en' => ' Bahrain',
                'country_ar' => 'البحرين',
                'nationality_en' => 'Bahraini',
                'nationality_ar' => 'بحريني',
            ],
            18 => [
                'code' => 'BD',
                'country_en' => ' Bangladesh',
                'country_ar' => 'بنغلاديش',
                'nationality_en' => 'Bangladeshi',
                'nationality_ar' => 'بنغلاديشي',
            ],
            19 => [
                'code' => 'BB',
                'country_en' => ' Barbados',
                'country_ar' => 'بربادوس',
                'nationality_en' => 'Barbadian',
                'nationality_ar' => 'بربادوسي',
            ],
            20 => [
                'code' => 'BY',
                'country_en' => ' Belarus',
                'country_ar' => 'روسيا البيضاء',
                'nationality_en' => 'Belarusian',
                'nationality_ar' => 'روسي',
            ],
            21 => [
                'code' => 'BE',
                'country_en' => ' Belgium',
                'country_ar' => 'بلجيكا',
                'nationality_en' => 'Belgian',
                'nationality_ar' => 'بلجيكي',
            ],
            22 => [
                'code' => 'BZ',
                'country_en' => ' Belize',
                'country_ar' => 'بيليز',
                'nationality_en' => 'Belizean',
                'nationality_ar' => 'بيليزي',
            ],
            23 => [
                'code' => 'BJ',
                'country_en' => ' Benin',
                'country_ar' => 'بنين',
                'nationality_en' => 'Beninese',
                'nationality_ar' => 'بنيني',
            ],
            24 => [
                'code' => 'BL',
                'country_en' => ' Saint Barthelemy',
                'country_ar' => 'سان بارتيلمي',
                'nationality_en' => 'Saint Barthelmian',
                'nationality_ar' => 'سان بارتيلمي',
            ],
            25 => [
                'code' => 'BM',
                'country_en' => ' Bermuda',
                'country_ar' => 'جزر برمودا',
                'nationality_en' => 'Bermudan',
                'nationality_ar' => 'برمودي',
            ],
            26 => [
                'code' => 'BT',
                'country_en' => ' Bhutan',
                'country_ar' => 'بوتان',
                'nationality_en' => 'Bhutanese',
                'nationality_ar' => 'بوتاني',
            ],
            27 => [
                'code' => 'BO',
                'country_en' => ' Bolivia',
                'country_ar' => 'بوليفيا',
                'nationality_en' => 'Bolivian',
                'nationality_ar' => 'بوليفي',
            ],
            28 => [
                'code' => 'BA',
                'country_en' => ' Bosnia and Herzegovina',
                'country_ar' => 'البوسنة و الهرسك',
                'nationality_en' => 'Bosnian / Herzegovinian',
                'nationality_ar' => 'بوسني/هرسكي',
            ],
            29 => [
                'code' => 'BW',
                'country_en' => ' Botswana',
                'country_ar' => 'بوتسوانا',
                'nationality_en' => 'Botswanan',
                'nationality_ar' => 'بوتسواني',
            ],
            30 => [
                'code' => 'BV',
                'country_en' => ' Bouvet Island',
                'country_ar' => 'جزيرة بوفيه',
                'nationality_en' => 'Bouvetian',
                'nationality_ar' => 'بوفيهي',
            ],
            31 => [
                'code' => 'BR',
                'country_en' => ' Brazil',
                'country_ar' => 'البرازيل',
                'nationality_en' => 'Brazilian',
                'nationality_ar' => 'برازيلي',
            ],
            32 => [
                'code' => 'IO',
                'country_en' => ' British Indian Ocean Territory',
                'country_ar' => 'إقليم المحيط الهندي البريطاني',
                'nationality_en' => 'British Indian Ocean Territory',
                'nationality_ar' => 'إقليم المحيط الهندي البريطاني',
            ],
            33 => [
                'code' => 'BN',
                'country_en' => ' Brunei Darussalam',
                'country_ar' => 'بروني',
                'nationality_en' => 'Bruneian',
                'nationality_ar' => 'بروني',
            ],
            34 => [
                'code' => 'BG',
                'country_en' => ' Bulgaria',
                'country_ar' => 'بلغاريا',
                'nationality_en' => 'Bulgarian',
                'nationality_ar' => 'بلغاري',
            ],
            35 => [
                'code' => 'BF',
                'country_en' => ' Burkina Faso',
                'country_ar' => 'بوركينا فاسو',
                'nationality_en' => 'Burkinabe',
                'nationality_ar' => 'بوركيني',
            ],
            36 => [
                'code' => 'BI',
                'country_en' => ' Burundi',
                'country_ar' => 'بوروندي',
                'nationality_en' => 'Burundian',
                'nationality_ar' => 'بورونيدي',
            ],
            37 => [
                'code' => 'KH',
                'country_en' => ' Cambodia',
                'country_ar' => 'كمبوديا',
                'nationality_en' => 'Cambodian',
                'nationality_ar' => 'كمبودي',
            ],
            38 => [
                'code' => 'CM',
                'country_en' => ' Cameroon',
                'country_ar' => 'كاميرون',
                'nationality_en' => 'Cameroonian',
                'nationality_ar' => 'كاميروني',
            ],
            39 => [
                'code' => 'CA',
                'country_en' => ' Canada',
                'country_ar' => 'كندا',
                'nationality_en' => 'Canadian',
                'nationality_ar' => 'كندي',
            ],
            40 => [
                'code' => 'CV',
                'country_en' => ' Cape Verde',
                'country_ar' => 'الرأس الأخضر',
                'nationality_en' => 'Cape Verdean',
                'nationality_ar' => 'الرأس الأخضر',
            ],
            41 => [
                'code' => 'KY',
                'country_en' => ' Cayman Islands',
                'country_ar' => 'جزر كايمان',
                'nationality_en' => 'Caymanian',
                'nationality_ar' => 'كايماني',
            ],
            42 => [
                'code' => 'CF',
                'country_en' => ' Central African Republic',
                'country_ar' => 'جمهورية أفريقيا الوسطى',
                'nationality_en' => 'Central African',
                'nationality_ar' => 'أفريقي',
            ],
            43 => [
                'code' => 'TD',
                'country_en' => ' Chad',
                'country_ar' => 'تشاد',
                'nationality_en' => 'Chadian',
                'nationality_ar' => 'تشادي',
            ],
            44 => [
                'code' => 'CL',
                'country_en' => ' Chile',
                'country_ar' => 'شيلي',
                'nationality_en' => 'Chilean',
                'nationality_ar' => 'شيلي',
            ],
            45 => [
                'code' => 'CN',
                'country_en' => ' China',
                'country_ar' => 'الصين',
                'nationality_en' => 'Chinese',
                'nationality_ar' => 'صيني',
            ],
            46 => [
                'code' => 'CX',
                'country_en' => ' Christmas Island',
                'country_ar' => 'جزيرة عيد الميلاد',
                'nationality_en' => 'Christmas Islander',
                'nationality_ar' => 'جزيرة عيد الميلاد',
            ],
            47 => [
                'code' => 'CC',
                'country_en' => ' Cocos (Keeling) Islands',
                'country_ar' => 'جزر كوكوس',
                'nationality_en' => 'Cocos Islander',
                'nationality_ar' => 'جزر كوكوس',
            ],
            48 => [
                'code' => 'CO',
                'country_en' => ' Colombia',
                'country_ar' => 'كولومبيا',
                'nationality_en' => 'Colombian',
                'nationality_ar' => 'كولومبي',
            ],
            49 => [
                'code' => 'KM',
                'country_en' => ' Comoros',
                'country_ar' => 'جزر القمر',
                'nationality_en' => 'Comorian',
                'nationality_ar' => 'جزر القمر',
            ],
            50 => [
                'code' => 'CG',
                'country_en' => ' Congo',
                'country_ar' => 'الكونغو',
                'nationality_en' => 'Congolese',
                'nationality_ar' => 'كونغي',
            ],
            51 => [
                'code' => 'CK',
                'country_en' => ' Cook Islands',
                'country_ar' => 'جزر كوك',
                'nationality_en' => 'Cook Islander',
                'nationality_ar' => 'جزر كوك',
            ],
            52 => [
                'code' => 'CR',
                'country_en' => ' Costa Rica',
                'country_ar' => 'كوستاريكا',
                'nationality_en' => 'Costa Rican',
                'nationality_ar' => 'كوستاريكي',
            ],
            53 => [
                'code' => 'HR',
                'country_en' => ' Croatia',
                'country_ar' => 'كرواتيا',
                'nationality_en' => 'Croatian',
                'nationality_ar' => 'كوراتي',
            ],
            54 => [
                'code' => 'CU',
                'country_en' => ' Cuba',
                'country_ar' => 'كوبا',
                'nationality_en' => 'Cuban',
                'nationality_ar' => 'كوبي',
            ],
            55 => [
                'code' => 'CY',
                'country_en' => ' Cyprus',
                'country_ar' => 'قبرص',
                'nationality_en' => 'Cypriot',
                'nationality_ar' => 'قبرصي',
            ],
            56 => [
                'code' => 'CW',
                'country_en' => ' Curaçao',
                'country_ar' => 'كوراساو',
                'nationality_en' => 'Curacian',
                'nationality_ar' => 'كوراساوي',
            ],
            57 => [
                'code' => 'CZ',
                'country_en' => ' Czech Republic',
                'country_ar' => 'الجمهورية التشيكية',
                'nationality_en' => 'Czech',
                'nationality_ar' => 'تشيكي',
            ],
            58 => [
                'code' => 'DK',
                'country_en' => ' Denmark',
                'country_ar' => 'الدانمارك',
                'nationality_en' => 'Danish',
                'nationality_ar' => 'دنماركي',
            ],
            59 => [
                'code' => 'DJ',
                'country_en' => ' Djibouti',
                'country_ar' => 'جيبوتي',
                'nationality_en' => 'Djiboutian',
                'nationality_ar' => 'جيبوتي',
            ],
            60 => [
                'code' => 'DM',
                'country_en' => ' Dominica',
                'country_ar' => 'دومينيكا',
                'nationality_en' => 'Dominican',
                'nationality_ar' => 'دومينيكي',
            ],
            61 => [
                'code' => 'DO',
                'country_en' => ' Dominican Republic',
                'country_ar' => 'الجمهورية الدومينيكية',
                'nationality_en' => 'Dominican',
                'nationality_ar' => 'دومينيكي',
            ],
            62 => [
                'code' => 'EC',
                'country_en' => ' Ecuador',
                'country_ar' => 'إكوادور',
                'nationality_en' => 'Ecuadorian',
                'nationality_ar' => 'إكوادوري',
            ],
            63 => [
                'code' => 'EG',
                'country_en' => ' Egypt',
                'country_ar' => 'مصر',
                'nationality_en' => 'Egyptian',
                'nationality_ar' => 'مصري',
            ],
            64 => [
                'code' => 'SV',
                'country_en' => ' El Salvador',
                'country_ar' => 'إلسلفادور',
                'nationality_en' => 'Salvadoran',
                'nationality_ar' => 'سلفادوري',
            ],
            65 => [
                'code' => 'GQ',
                'country_en' => ' Equatorial Guinea',
                'country_ar' => 'غينيا الاستوائي',
                'nationality_en' => 'Equatorial Guinean',
                'nationality_ar' => 'غيني',
            ],
            66 => [
                'code' => 'ER',
                'country_en' => ' Eritrea',
                'country_ar' => 'إريتريا',
                'nationality_en' => 'Eritrean',
                'nationality_ar' => 'إريتيري',
            ],
            67 => [
                'code' => 'EE',
                'country_en' => ' Estonia',
                'country_ar' => 'استونيا',
                'nationality_en' => 'Estonian',
                'nationality_ar' => 'استوني',
            ],
            68 => [
                'code' => 'ET',
                'country_en' => ' Ethiopia',
                'country_ar' => 'أثيوبيا',
                'nationality_en' => 'Ethiopian',
                'nationality_ar' => 'أثيوبي',
            ],
            69 => [
                'code' => 'FK',
                'country_en' => ' Falkland Islands (Malvinas)',
                'country_ar' => 'جزر فوكلاند',
                'nationality_en' => 'Falkland Islander',
                'nationality_ar' => 'فوكلاندي',
            ],
            70 => [
                'code' => 'FO',
                'country_en' => ' Faroe Islands',
                'country_ar' => 'جزر فارو',
                'nationality_en' => 'Faroese',
                'nationality_ar' => 'جزر فارو',
            ],
            71 => [
                'code' => 'FJ',
                'country_en' => ' Fiji',
                'country_ar' => 'فيجي',
                'nationality_en' => 'Fijian',
                'nationality_ar' => 'فيجي',
            ],
            72 => [
                'code' => 'FI',
                'country_en' => ' Finland',
                'country_ar' => 'فنلندا',
                'nationality_en' => 'Finnish',
                'nationality_ar' => 'فنلندي',
            ],
            73 => [
                'code' => 'FR',
                'country_en' => ' France',
                'country_ar' => 'فرنسا',
                'nationality_en' => 'French',
                'nationality_ar' => 'فرنسي',
            ],
            74 => [
                'code' => 'GF',
                'country_en' => ' French Guiana',
                'country_ar' => 'غويانا الفرنسية',
                'nationality_en' => 'French Guianese',
                'nationality_ar' => 'غويانا الفرنسية',
            ],
            75 => [
                'code' => 'PF',
                'country_en' => ' French Polynesia',
                'country_ar' => 'بولينيزيا الفرنسية',
                'nationality_en' => 'French Polynesian',
                'nationality_ar' => 'بولينيزيي',
            ],
            76 => [
                'code' => 'TF',
                'country_en' => ' French Southern and Antarctic Lands',
                'country_ar' => 'أراض فرنسية جنوبية وأنتارتيكية',
                'nationality_en' => 'French',
                'nationality_ar' => 'أراض فرنسية جنوبية وأنتارتيكية',
            ],
            77 => [
                'code' => 'GA',
                'country_en' => ' Gabon',
                'country_ar' => 'الغابون',
                'nationality_en' => 'Gabonese',
                'nationality_ar' => 'غابوني',
            ],
            78 => [
                'code' => 'GM',
                'country_en' => ' Gambia',
                'country_ar' => 'غامبيا',
                'nationality_en' => 'Gambian',
                'nationality_ar' => 'غامبي',
            ],
            79 => [
                'code' => 'GE',
                'country_en' => ' Georgia',
                'country_ar' => 'جيورجيا',
                'nationality_en' => 'Georgian',
                'nationality_ar' => 'جيورجي',
            ],
            80 => [
                'code' => 'DE',
                'country_en' => ' Germany',
                'country_ar' => 'ألمانيا',
                'nationality_en' => 'German',
                'nationality_ar' => 'ألماني',
            ],
            81 => [
                'code' => 'GH',
                'country_en' => ' Ghana',
                'country_ar' => 'غانا',
                'nationality_en' => 'Ghanaian',
                'nationality_ar' => 'غاني',
            ],
            82 => [
                'code' => 'GI',
                'country_en' => ' Gibraltar',
                'country_ar' => 'جبل طارق',
                'nationality_en' => 'Gibraltar',
                'nationality_ar' => 'جبل طارق',
            ],
            83 => [
                'code' => 'GG',
                'country_en' => ' Guernsey',
                'country_ar' => 'غيرنزي',
                'nationality_en' => 'Guernsian',
                'nationality_ar' => 'غيرنزي',
            ],
            84 => [
                'code' => 'GR',
                'country_en' => ' Greece',
                'country_ar' => 'اليونان',
                'nationality_en' => 'Greek',
                'nationality_ar' => 'يوناني',
            ],
            85 => [
                'code' => 'GL',
                'country_en' => ' Greenland',
                'country_ar' => 'جرينلاند',
                'nationality_en' => 'Greenlandic',
                'nationality_ar' => 'جرينلاندي',
            ],
            86 => [
                'code' => 'GD',
                'country_en' => ' Grenada',
                'country_ar' => 'غرينادا',
                'nationality_en' => 'Grenadian',
                'nationality_ar' => 'غرينادي',
            ],
            87 => [
                'code' => 'GP',
                'country_en' => ' Guadeloupe',
                'country_ar' => 'جزر جوادلوب',
                'nationality_en' => 'Guadeloupe',
                'nationality_ar' => 'جزر جوادلوب',
            ],
            88 => [
                'code' => 'GU',
                'country_en' => ' Guam',
                'country_ar' => 'جوام',
                'nationality_en' => 'Guamanian',
                'nationality_ar' => 'جوامي',
            ],
            89 => [
                'code' => 'GT',
                'country_en' => ' Guatemala',
                'country_ar' => 'غواتيمال',
                'nationality_en' => 'Guatemalan',
                'nationality_ar' => 'غواتيمالي',
            ],
            90 => [
                'code' => 'GN',
                'country_en' => ' Guinea',
                'country_ar' => 'غينيا',
                'nationality_en' => 'Guinean',
                'nationality_ar' => 'غيني',
            ],
            91 => [
                'code' => 'GW',
                'country_en' => ' Guinea-Bissau',
                'country_ar' => 'غينيا-بيساو',
                'nationality_en' => 'Guinea-Bissauan',
                'nationality_ar' => 'غيني',
            ],
            92 => [
                'code' => 'GY',
                'country_en' => ' Guyana',
                'country_ar' => 'غيانا',
                'nationality_en' => 'Guyanese',
                'nationality_ar' => 'غياني',
            ],
            93 => [
                'code' => 'HT',
                'country_en' => ' Haiti',
                'country_ar' => 'هايتي',
                'nationality_en' => 'Haitian',
                'nationality_ar' => 'هايتي',
            ],
            94 => [
                'code' => 'HM',
                'country_en' => ' Heard and Mc Donald Islands',
                'country_ar' => 'جزيرة هيرد وجزر ماكدونالد',
                'nationality_en' => 'Heard and Mc Donald Islanders',
                'nationality_ar' => 'جزيرة هيرد وجزر ماكدونالد',
            ],
            95 => [
                'code' => 'HN',
                'country_en' => ' Honduras',
                'country_ar' => 'هندوراس',
                'nationality_en' => 'Honduran',
                'nationality_ar' => 'هندوراسي',
            ],
            96 => [
                'code' => 'HK',
                'country_en' => ' Hong Kong',
                'country_ar' => 'هونغ كونغ',
                'nationality_en' => 'Hongkongese',
                'nationality_ar' => 'هونغ كونغي',
            ],
            97 => [
                'code' => 'HU',
                'country_en' => ' Hungary',
                'country_ar' => 'المجر',
                'nationality_en' => 'Hungarian',
                'nationality_ar' => 'مجري',
            ],
            98 => [
                'code' => 'IS',
                'country_en' => ' Iceland',
                'country_ar' => 'آيسلندا',
                'nationality_en' => 'Icelandic',
                'nationality_ar' => 'آيسلندي',
            ],
            99 => [
                'code' => 'IN',
                'country_en' => ' India',
                'country_ar' => 'الهند',
                'nationality_en' => 'Indian',
                'nationality_ar' => 'هندي',
            ],
            100 => [
                'code' => 'IM',
                'country_en' => ' Isle of Man',
                'country_ar' => 'جزيرة مان',
                'nationality_en' => 'Manx',
                'nationality_ar' => 'ماني',
            ],
            101 => [
                'code' => 'ID',
                'country_en' => ' Indonesia',
                'country_ar' => 'أندونيسيا',
                'nationality_en' => 'Indonesian',
                'nationality_ar' => 'أندونيسيي',
            ],
            102 => [
                'code' => 'IR',
                'country_en' => ' Iran',
                'country_ar' => 'إيران',
                'nationality_en' => 'Iranian',
                'nationality_ar' => 'إيراني',
            ],
            103 => [
                'code' => 'IQ',
                'country_en' => ' Iraq',
                'country_ar' => 'العراق',
                'nationality_en' => 'Iraqi',
                'nationality_ar' => 'عراقي',
            ],
            104 => [
                'code' => 'IE',
                'country_en' => ' Ireland',
                'country_ar' => 'إيرلندا',
                'nationality_en' => 'Irish',
                'nationality_ar' => 'إيرلندي',
            ],
            105 => [
                'code' => 'IT',
                'country_en' => ' Italy',
                'country_ar' => 'إيطاليا',
                'nationality_en' => 'Italian',
                'nationality_ar' => 'إيطالي',
            ],
            106 => [
                'code' => 'CI',
                'country_en' => ' Ivory Coast',
                'country_ar' => 'ساحل العاج',
                'nationality_en' => 'Ivory Coastian',
                'nationality_ar' => 'ساحل العاج',
            ],
            107 => [
                'code' => 'JE',
                'country_en' => ' Jersey',
                'country_ar' => 'جيرزي',
                'nationality_en' => 'Jersian',
                'nationality_ar' => 'جيرزي',
            ],
            108 => [
                'code' => 'JM',
                'country_en' => ' Jamaica',
                'country_ar' => 'جمايكا',
                'nationality_en' => 'Jamaican',
                'nationality_ar' => 'جمايكي',
            ],
            109 => [
                'code' => 'JP',
                'country_en' => ' Japan',
                'country_ar' => 'اليابان',
                'nationality_en' => 'Japanese',
                'nationality_ar' => 'ياباني',
            ],
            110 => [
                'code' => 'JO',
                'country_en' => ' Jordan',
                'country_ar' => 'الأردن',
                'nationality_en' => 'Jordanian',
                'nationality_ar' => 'أردني',
            ],
            111 => [
                'code' => 'KZ',
                'country_en' => ' Kazakhstan',
                'country_ar' => 'كازاخستان',
                'nationality_en' => 'Kazakh',
                'nationality_ar' => 'كازاخستاني',
            ],
            112 => [
                'code' => 'KE',
                'country_en' => ' Kenya',
                'country_ar' => 'كينيا',
                'nationality_en' => 'Kenyan',
                'nationality_ar' => 'كيني',
            ],
            113 => [
                'code' => 'KI',
                'country_en' => ' Kiribati',
                'country_ar' => 'كيريباتي',
                'nationality_en' => 'I-Kiribati',
                'nationality_ar' => 'كيريباتي',
            ],
            114 => [
                'code' => 'KP',
                'country_en' => ' Korea(North Korea)',
                'country_ar' => 'كوريا الشمالية',
                'nationality_en' => 'North Korean',
                'nationality_ar' => 'كوري',
            ],
            115 => [
                'code' => 'KR',
                'country_en' => ' Korea(South Korea)',
                'country_ar' => 'كوريا الجنوبية',
                'nationality_en' => 'South Korean',
                'nationality_ar' => 'كوري',
            ],
            116 => [
                'code' => 'XK',
                'country_en' => ' Kosovo',
                'country_ar' => 'كوسوفو',
                'nationality_en' => 'Kosovar',
                'nationality_ar' => 'كوسيفي',
            ],
            117 => [
                'code' => 'KW',
                'country_en' => ' Kuwait',
                'country_ar' => 'الكويت',
                'nationality_en' => 'Kuwaiti',
                'nationality_ar' => 'كويتي',
            ],
            118 => [
                'code' => 'KG',
                'country_en' => ' Kyrgyzstan',
                'country_ar' => 'قيرغيزستان',
                'nationality_en' => 'Kyrgyzstani',
                'nationality_ar' => 'قيرغيزستاني',
            ],
            119 => [
                'code' => 'LA',
                'country_en' => ' Lao PDR',
                'country_ar' => 'لاوس',
                'nationality_en' => 'Laotian',
                'nationality_ar' => 'لاوسي',
            ],
            120 => [
                'code' => 'LV',
                'country_en' => ' Latvia',
                'country_ar' => 'لاتفيا',
                'nationality_en' => 'Latvian',
                'nationality_ar' => 'لاتيفي',
            ],
            121 => [
                'code' => 'LB',
                'country_en' => ' Lebanon',
                'country_ar' => 'لبنان',
                'nationality_en' => 'Lebanese',
                'nationality_ar' => 'لبناني',
            ],
            122 => [
                'code' => 'LS',
                'country_en' => ' Lesotho',
                'country_ar' => 'ليسوتو',
                'nationality_en' => 'Basotho',
                'nationality_ar' => 'ليوسيتي',
            ],
            123 => [
                'code' => 'LR',
                'country_en' => ' Liberia',
                'country_ar' => 'ليبيريا',
                'nationality_en' => 'Liberian',
                'nationality_ar' => 'ليبيري',
            ],
            124 => [
                'code' => 'LY',
                'country_en' => ' Libya',
                'country_ar' => 'ليبيا',
                'nationality_en' => 'Libyan',
                'nationality_ar' => 'ليبي',
            ],
            125 => [
                'code' => 'LI',
                'country_en' => ' Liechtenstein',
                'country_ar' => 'ليختنشتين',
                'nationality_en' => 'Liechtenstein',
                'nationality_ar' => 'ليختنشتيني',
            ],
            126 => [
                'code' => 'LT',
                'country_en' => ' Lithuania',
                'country_ar' => 'لتوانيا',
                'nationality_en' => 'Lithuanian',
                'nationality_ar' => 'لتوانيي',
            ],
            127 => [
                'code' => 'LU',
                'country_en' => ' Luxembourg',
                'country_ar' => 'لوكسمبورغ',
                'nationality_en' => 'Luxembourger',
                'nationality_ar' => 'لوكسمبورغي',
            ],
            128 => [
                'code' => 'LK',
                'country_en' => ' Sri Lanka',
                'country_ar' => 'سريلانكا',
                'nationality_en' => 'Sri Lankian',
                'nationality_ar' => 'سريلانكي',
            ],
            129 => [
                'code' => 'MO',
                'country_en' => ' Macau',
                'country_ar' => 'ماكاو',
                'nationality_en' => 'Macanese',
                'nationality_ar' => 'ماكاوي',
            ],
            130 => [
                'code' => 'MK',
                'country_en' => ' Macedonia',
                'country_ar' => 'مقدونيا',
                'nationality_en' => 'Macedonian',
                'nationality_ar' => 'مقدوني',
            ],
            131 => [
                'code' => 'MG',
                'country_en' => ' Madagascar',
                'country_ar' => 'مدغشقر',
                'nationality_en' => 'Malagasy',
                'nationality_ar' => 'مدغشقري',
            ],
            132 => [
                'code' => 'MW',
                'country_en' => ' Malawi',
                'country_ar' => 'مالاوي',
                'nationality_en' => 'Malawian',
                'nationality_ar' => 'مالاوي',
            ],
            133 => [
                'code' => 'MY',
                'country_en' => ' Malaysia',
                'country_ar' => 'ماليزيا',
                'nationality_en' => 'Malaysian',
                'nationality_ar' => 'ماليزي',
            ],
            134 => [
                'code' => 'MV',
                'country_en' => ' Maldives',
                'country_ar' => 'المالديف',
                'nationality_en' => 'Maldivian',
                'nationality_ar' => 'مالديفي',
            ],
            135 => [
                'code' => 'ML',
                'country_en' => ' Mali',
                'country_ar' => 'مالي',
                'nationality_en' => 'Malian',
                'nationality_ar' => 'مالي',
            ],
            136 => [
                'code' => 'MT',
                'country_en' => ' Malta',
                'country_ar' => 'مالطا',
                'nationality_en' => 'Maltese',
                'nationality_ar' => 'مالطي',
            ],
            137 => [
                'code' => 'MH',
                'country_en' => ' Marshall Islands',
                'country_ar' => 'جزر مارشال',
                'nationality_en' => 'Marshallese',
                'nationality_ar' => 'مارشالي',
            ],
            138 => [
                'code' => 'MQ',
                'country_en' => ' Martinique',
                'country_ar' => 'مارتينيك',
                'nationality_en' => 'Martiniquais',
                'nationality_ar' => 'مارتينيكي',
            ],
            139 => [
                'code' => 'MR',
                'country_en' => ' Mauritania',
                'country_ar' => 'موريتانيا',
                'nationality_en' => 'Mauritanian',
                'nationality_ar' => 'موريتانيي',
            ],
            140 => [
                'code' => 'MU',
                'country_en' => ' Mauritius',
                'country_ar' => 'موريشيوس',
                'nationality_en' => 'Mauritian',
                'nationality_ar' => 'موريشيوسي',
            ],
            141 => [
                'code' => 'YT',
                'country_en' => ' Mayotte',
                'country_ar' => 'مايوت',
                'nationality_en' => 'Mahoran',
                'nationality_ar' => 'مايوتي',
            ],
            142 => [
                'code' => 'MX',
                'country_en' => ' Mexico',
                'country_ar' => 'المكسيك',
                'nationality_en' => 'Mexican',
                'nationality_ar' => 'مكسيكي',
            ],
            143 => [
                'code' => 'FM',
                'country_en' => ' Micronesia',
                'country_ar' => 'مايكرونيزيا',
                'nationality_en' => 'Micronesian',
                'nationality_ar' => 'مايكرونيزيي',
            ],
            144 => [
                'code' => 'MD',
                'country_en' => ' Moldova',
                'country_ar' => 'مولدافيا',
                'nationality_en' => 'Moldovan',
                'nationality_ar' => 'مولديفي',
            ],
            145 => [
                'code' => 'MC',
                'country_en' => ' Monaco',
                'country_ar' => 'موناكو',
                'nationality_en' => 'Monacan',
                'nationality_ar' => 'مونيكي',
            ],
            146 => [
                'code' => 'MN',
                'country_en' => ' Mongolia',
                'country_ar' => 'منغوليا',
                'nationality_en' => 'Mongolian',
                'nationality_ar' => 'منغولي',
            ],
            147 => [
                'code' => 'ME',
                'country_en' => ' Montenegro',
                'country_ar' => 'الجبل الأسود',
                'nationality_en' => 'Montenegrin',
                'nationality_ar' => 'الجبل الأسود',
            ],
            148 => [
                'code' => 'MS',
                'country_en' => ' Montserrat',
                'country_ar' => 'مونتسيرات',
                'nationality_en' => 'Montserratian',
                'nationality_ar' => 'مونتسيراتي',
            ],
            149 => [
                'code' => 'MA',
                'country_en' => ' Morocco',
                'country_ar' => 'المغرب',
                'nationality_en' => 'Moroccan',
                'nationality_ar' => 'مغربي',
            ],
            150 => [
                'code' => 'MZ',
                'country_en' => ' Mozambique',
                'country_ar' => 'موزمبيق',
                'nationality_en' => 'Mozambican',
                'nationality_ar' => 'موزمبيقي',
            ],
            151 => [
                'code' => 'MM',
                'country_en' => ' Myanmar',
                'country_ar' => 'ميانمار',
                'nationality_en' => 'Myanmarian',
                'nationality_ar' => 'ميانماري',
            ],
            152 => [
                'code' => 'NA',
                'country_en' => ' Namibia',
                'country_ar' => 'ناميبيا',
                'nationality_en' => 'Namibian',
                'nationality_ar' => 'ناميبي',
            ],
            153 => [
                'code' => 'NR',
                'country_en' => ' Nauru',
                'country_ar' => 'نورو',
                'nationality_en' => 'Nauruan',
                'nationality_ar' => 'نوري',
            ],
            154 => [
                'code' => 'NP',
                'country_en' => ' Nepal',
                'country_ar' => 'نيبال',
                'nationality_en' => 'Nepalese',
                'nationality_ar' => 'نيبالي',
            ],
            155 => [
                'code' => 'NL',
                'country_en' => ' Netherlands',
                'country_ar' => 'هولندا',
                'nationality_en' => 'Dutch',
                'nationality_ar' => 'هولندي',
            ],
            156 => [
                'code' => 'AN',
                'country_en' => ' Netherlands Antilles',
                'country_ar' => 'جزر الأنتيل الهولندي',
                'nationality_en' => 'Dutch Antilier',
                'nationality_ar' => 'هولندي',
            ],
            157 => [
                'code' => 'NC',
                'country_en' => ' New Caledonia',
                'country_ar' => 'كاليدونيا الجديدة',
                'nationality_en' => 'New Caledonian',
                'nationality_ar' => 'كاليدوني',
            ],
            158 => [
                'code' => 'NZ',
                'country_en' => ' New Zealand',
                'country_ar' => 'نيوزيلندا',
                'nationality_en' => 'New Zealander',
                'nationality_ar' => 'نيوزيلندي',
            ],
            159 => [
                'code' => 'NI',
                'country_en' => ' Nicaragua',
                'country_ar' => 'نيكاراجوا',
                'nationality_en' => 'Nicaraguan',
                'nationality_ar' => 'نيكاراجوي',
            ],
            160 => [
                'code' => 'NE',
                'country_en' => ' Niger',
                'country_ar' => 'النيجر',
                'nationality_en' => 'Nigerien',
                'nationality_ar' => 'نيجيري',
            ],
            161 => [
                'code' => 'NG',
                'country_en' => ' Nigeria',
                'country_ar' => 'نيجيريا',
                'nationality_en' => 'Nigerian',
                'nationality_ar' => 'نيجيري',
            ],
            162 => [
                'code' => 'NU',
                'country_en' => ' Niue',
                'country_ar' => 'ني',
                'nationality_en' => 'Niuean',
                'nationality_ar' => 'ني',
            ],
            163 => [
                'code' => 'NF',
                'country_en' => ' Norfolk Island',
                'country_ar' => 'جزيرة نورفولك',
                'nationality_en' => 'Norfolk Islander',
                'nationality_ar' => 'نورفوليكي',
            ],
            164 => [
                'code' => 'MP',
                'country_en' => ' Northern Mariana Islands',
                'country_ar' => 'جزر ماريانا الشمالية',
                'nationality_en' => 'Northern Marianan',
                'nationality_ar' => 'ماريني',
            ],
            165 => [
                'code' => 'NO',
                'country_en' => ' Norway',
                'country_ar' => 'النرويج',
                'nationality_en' => 'Norwegian',
                'nationality_ar' => 'نرويجي',
            ],
            166 => [
                'code' => 'OM',
                'country_en' => ' Oman',
                'country_ar' => 'عمان',
                'nationality_en' => 'Omani',
                'nationality_ar' => 'عماني',
            ],
            167 => [
                'code' => 'PK',
                'country_en' => ' Pakistan',
                'country_ar' => 'باكستان',
                'nationality_en' => 'Pakistani',
                'nationality_ar' => 'باكستاني',
            ],
            168 => [
                'code' => 'PW',
                'country_en' => ' Palau',
                'country_ar' => 'بالاو',
                'nationality_en' => 'Palauan',
                'nationality_ar' => 'بالاوي',
            ],
            169 => [
                'code' => 'PS',
                'country_en' => ' Palestine',
                'country_ar' => 'فلسطين',
                'nationality_en' => 'Palestinian',
                'nationality_ar' => 'فلسطيني',
            ],
            170 => [
                'code' => 'PA',
                'country_en' => ' Panama',
                'country_ar' => 'بنما',
                'nationality_en' => 'Panamanian',
                'nationality_ar' => 'بنمي',
            ],
            171 => [
                'code' => 'PG',
                'country_en' => ' Papua New Guinea',
                'country_ar' => 'بابوا غينيا الجديدة',
                'nationality_en' => 'Papua New Guinean',
                'nationality_ar' => 'بابوي',
            ],
            172 => [
                'code' => 'PY',
                'country_en' => ' Paraguay',
                'country_ar' => 'باراغواي',
                'nationality_en' => 'Paraguayan',
                'nationality_ar' => 'بارغاوي',
            ],
            173 => [
                'code' => 'PE',
                'country_en' => ' Peru',
                'country_ar' => 'بيرو',
                'nationality_en' => 'Peruvian',
                'nationality_ar' => 'بيري',
            ],
            174 => [
                'code' => 'PH',
                'country_en' => ' Philippines',
                'country_ar' => 'الفليبين',
                'nationality_en' => 'Filipino',
                'nationality_ar' => 'فلبيني',
            ],
            175 => [
                'code' => 'PN',
                'country_en' => ' Pitcairn',
                'country_ar' => 'بيتكيرن',
                'nationality_en' => 'Pitcairn Islander',
                'nationality_ar' => 'بيتكيرني',
            ],
            176 => [
                'code' => 'PL',
                'country_en' => ' Poland',
                'country_ar' => 'بولونيا',
                'nationality_en' => 'Polish',
                'nationality_ar' => 'بوليني',
            ],
            177 => [
                'code' => 'PT',
                'country_en' => ' Portugal',
                'country_ar' => 'البرتغال',
                'nationality_en' => 'Portuguese',
                'nationality_ar' => 'برتغالي',
            ],
            178 => [
                'code' => 'PR',
                'country_en' => ' Puerto Rico',
                'country_ar' => 'بورتو ريكو',
                'nationality_en' => 'Puerto Rican',
                'nationality_ar' => 'بورتي',
            ],
            179 => [
                'code' => 'QA',
                'country_en' => ' Qatar',
                'country_ar' => 'قطر',
                'nationality_en' => 'Qatari',
                'nationality_ar' => 'قطري',
            ],
            180 => [
                'code' => 'RE',
                'country_en' => ' Reunion Island',
                'country_ar' => 'ريونيون',
                'nationality_en' => 'Reunionese',
                'nationality_ar' => 'ريونيوني',
            ],
            181 => [
                'code' => 'RO',
                'country_en' => ' Romania',
                'country_ar' => 'رومانيا',
                'nationality_en' => 'Romanian',
                'nationality_ar' => 'روماني',
            ],
            182 => [
                'code' => 'RU',
                'country_en' => ' Russian',
                'country_ar' => 'روسيا',
                'nationality_en' => 'Russian',
                'nationality_ar' => 'روسي',
            ],
            183 => [
                'code' => 'RW',
                'country_en' => ' Rwanda',
                'country_ar' => 'رواندا',
                'nationality_en' => 'Rwandan',
                'nationality_ar' => 'رواندا',
            ],
            184 => [
                'code' => 'KN',
                'country_en' => ' Saint Kitts and Nevis',
                'country_ar' => 'سانت كيتس ونيفس',
                'nationality_en' => '',
                'nationality_ar' => 'Kittitian/Nevisian',
            ],
            185 => [
                'code' => 'MF',
                'country_en' => ' Saint Martin (French part)',
                'country_ar' => 'ساينت مارتن فرنسي',
                'nationality_en' => 'St. Martian(French)',
                'nationality_ar' => 'ساينت مارتني فرنسي',
            ],
            186 => [
                'code' => 'SX',
                'country_en' => ' Sint Maarten (Dutch part)',
                'country_ar' => 'ساينت مارتن هولندي',
                'nationality_en' => 'St. Martian(Dutch)',
                'nationality_ar' => 'ساينت مارتني هولندي',
            ],
            187 => [
                'code' => 'LC',
                'country_en' => ' Saint Pierre and Miquelon',
                'country_ar' => 'سان بيير وميكلون',
                'nationality_en' => 'St. Pierre and Miquelon',
                'nationality_ar' => 'سان بيير وميكلوني',
            ],
            188 => [
                'code' => 'VC',
                'country_en' => ' Saint Vincent and the Grenadines',
                'country_ar' => 'سانت فنسنت وجزر غرينادين',
                'nationality_en' => 'Saint Vincent and the Grenadines',
                'nationality_ar' => 'سانت فنسنت وجزر غرينادين',
            ],
            189 => [
                'code' => 'WS',
                'country_en' => ' Samoa',
                'country_ar' => 'ساموا',
                'nationality_en' => 'Samoan',
                'nationality_ar' => 'ساموي',
            ],
            190 => [
                'code' => 'SM',
                'country_en' => ' San Marino',
                'country_ar' => 'سان مارينو',
                'nationality_en' => 'Sammarinese',
                'nationality_ar' => 'ماريني',
            ],
            191 => [
                'code' => 'ST',
                'country_en' => ' Sao Tome and Principe',
                'country_ar' => 'ساو تومي وبرينسيبي',
                'nationality_en' => 'Sao Tomean',
                'nationality_ar' => 'ساو تومي وبرينسيبي',
            ],
            192 => [
                'code' => 'SA',
                'country_en' => ' Saudi Arabia',
                'country_ar' => 'المملكة العربية السعودية',
                'nationality_en' => 'Saudi Arabian',
                'nationality_ar' => 'سعودي',
            ],
            193 => [
                'code' => 'SN',
                'country_en' => ' Senegal',
                'country_ar' => 'السنغال',
                'nationality_en' => 'Senegalese',
                'nationality_ar' => 'سنغالي',
            ],
            194 => [
                'code' => 'RS',
                'country_en' => ' Serbia',
                'country_ar' => 'صربيا',
                'nationality_en' => 'Serbian',
                'nationality_ar' => 'صربي',
            ],
            195 => [
                'code' => 'SC',
                'country_en' => ' Seychelles',
                'country_ar' => 'سيشيل',
                'nationality_en' => 'Seychellois',
                'nationality_ar' => 'سيشيلي',
            ],
            196 => [
                'code' => 'SL',
                'country_en' => ' Sierra Leone',
                'country_ar' => 'سيراليون',
                'nationality_en' => 'Sierra Leonean',
                'nationality_ar' => 'سيراليوني',
            ],
            197 => [
                'code' => 'SG',
                'country_en' => ' Singapore',
                'country_ar' => 'سنغافورة',
                'nationality_en' => 'Singaporean',
                'nationality_ar' => 'سنغافوري',
            ],
            198 => [
                'code' => 'SK',
                'country_en' => ' Slovakia',
                'country_ar' => 'سلوفاكيا',
                'nationality_en' => 'Slovak',
                'nationality_ar' => 'سولفاكي',
            ],
            199 => [
                'code' => 'SI',
                'country_en' => ' Slovenia',
                'country_ar' => 'سلوفينيا',
                'nationality_en' => 'Slovenian',
                'nationality_ar' => 'سولفيني',
            ],
            200 => [
                'code' => 'SB',
                'country_en' => ' Solomon Islands',
                'country_ar' => 'جزر سليمان',
                'nationality_en' => 'Solomon Island',
                'nationality_ar' => 'جزر سليمان',
            ],
            201 => [
                'code' => 'SO',
                'country_en' => ' Somalia',
                'country_ar' => 'الصومال',
                'nationality_en' => 'Somali',
                'nationality_ar' => 'صومالي',
            ],
            202 => [
                'code' => 'ZA',
                'country_en' => ' South Africa',
                'country_ar' => 'جنوب أفريقيا',
                'nationality_en' => 'South African',
                'nationality_ar' => 'أفريقي',
            ],
            203 => [
                'code' => 'GS',
                'country_en' => ' South Georgia and the South Sandwich',
                'country_ar' => 'المنطقة القطبية الجنوبية',
                'nationality_en' => 'South Georgia and the South Sandwich',
                'nationality_ar' => 'لمنطقة القطبية الجنوبية',
            ],
            204 => [
                'code' => 'SS',
                'country_en' => ' South Sudan',
                'country_ar' => 'السودان الجنوبي',
                'nationality_en' => 'South Sudanese',
                'nationality_ar' => 'سوادني جنوبي',
            ],
            205 => [
                'code' => 'ES',
                'country_en' => ' Spain',
                'country_ar' => 'إسبانيا',
                'nationality_en' => 'Spanish',
                'nationality_ar' => 'إسباني',
            ],
            206 => [
                'code' => 'SH',
                'country_en' => ' Saint Helena',
                'country_ar' => 'سانت هيلانة',
                'nationality_en' => 'St. Helenian',
                'nationality_ar' => 'هيلاني',
            ],
            207 => [
                'code' => 'SD',
                'country_en' => ' Sudan',
                'country_ar' => 'السودان',
                'nationality_en' => 'Sudanese',
                'nationality_ar' => 'سوداني',
            ],
            208 => [
                'code' => 'SR',
                'country_en' => ' Suriname',
                'country_ar' => 'سورينام',
                'nationality_en' => 'Surinamese',
                'nationality_ar' => 'سورينامي',
            ],
            209 => [
                'code' => 'SJ',
                'country_en' => ' Svalbard and Jan Mayen',
                'country_ar' => 'سفالبارد ويان ماين',
                'nationality_en' => 'Svalbardian/Jan Mayenian',
                'nationality_ar' => 'سفالبارد ويان ماين',
            ],
            210 => [
                'code' => 'SZ',
                'country_en' => ' Swaziland',
                'country_ar' => 'سوازيلند',
                'nationality_en' => 'Swazi',
                'nationality_ar' => 'سوازيلندي',
            ],
            211 => [
                'code' => 'SE',
                'country_en' => ' Sweden',
                'country_ar' => 'السويد',
                'nationality_en' => 'Swedish',
                'nationality_ar' => 'سويدي',
            ],
            212 => [
                'code' => 'CH',
                'country_en' => ' Switzerland',
                'country_ar' => 'سويسرا',
                'nationality_en' => 'Swiss',
                'nationality_ar' => 'سويسري',
            ],
            213 => [
                'code' => 'SY',
                'country_en' => ' Syria',
                'country_ar' => 'سوريا',
                'nationality_en' => 'Syrian',
                'nationality_ar' => 'سوري',
            ],
            214 => [
                'code' => 'TW',
                'country_en' => ' Taiwan',
                'country_ar' => 'تايوان',
                'nationality_en' => 'Taiwanese',
                'nationality_ar' => 'تايواني',
            ],
            215 => [
                'code' => 'TJ',
                'country_en' => ' Tajikistan',
                'country_ar' => 'طاجيكستان',
                'nationality_en' => 'Tajikistani',
                'nationality_ar' => 'طاجيكستاني',
            ],
            216 => [
                'code' => 'TZ',
                'country_en' => ' Tanzania',
                'country_ar' => 'تنزانيا',
                'nationality_en' => 'Tanzanian',
                'nationality_ar' => 'تنزانيي',
            ],
            217 => [
                'code' => 'TH',
                'country_en' => ' Thailand',
                'country_ar' => 'تايلندا',
                'nationality_en' => 'Thai',
                'nationality_ar' => 'تايلندي',
            ],
            218 => [
                'code' => 'TL',
                'country_en' => ' Timor-Leste',
                'country_ar' => 'تيمور الشرقية',
                'nationality_en' => 'Timor-Lestian',
                'nationality_ar' => 'تيموري',
            ],
            219 => [
                'code' => 'TG',
                'country_en' => ' Togo',
                'country_ar' => 'توغو',
                'nationality_en' => 'Togolese',
                'nationality_ar' => 'توغي',
            ],
            220 => [
                'code' => 'TK',
                'country_en' => ' Tokelau',
                'country_ar' => 'توكيلاو',
                'nationality_en' => 'Tokelaian',
                'nationality_ar' => 'توكيلاوي',
            ],
            221 => [
                'code' => 'TO',
                'country_en' => ' Tonga',
                'country_ar' => 'تونغا',
                'nationality_en' => 'Tongan',
                'nationality_ar' => 'تونغي',
            ],
            222 => [
                'code' => 'TT',
                'country_en' => ' Trinidad and Tobago',
                'country_ar' => 'ترينيداد وتوباغو',
                'nationality_en' => 'Trinidadian/Tobagonian',
                'nationality_ar' => 'ترينيداد وتوباغو',
            ],
            223 => [
                'code' => 'TN',
                'country_en' => ' Tunisia',
                'country_ar' => 'تونس',
                'nationality_en' => 'Tunisian',
                'nationality_ar' => 'تونسي',
            ],
            224 => [
                'code' => 'TR',
                'country_en' => ' Turkey',
                'country_ar' => 'تركيا',
                'nationality_en' => 'Turkish',
                'nationality_ar' => 'تركي',
            ],
            225 => [
                'code' => 'TM',
                'country_en' => ' Turkmenistan',
                'country_ar' => 'تركمانستان',
                'nationality_en' => 'Turkmen',
                'nationality_ar' => 'تركمانستاني',
            ],
            226 => [
                'code' => 'TC',
                'country_en' => ' Turks and Caicos Islands',
                'country_ar' => 'جزر توركس وكايكوس',
                'nationality_en' => 'Turks and Caicos Islands',
                'nationality_ar' => 'جزر توركس وكايكوس',
            ],
            227 => [
                'code' => 'TV',
                'country_en' => ' Tuvalu',
                'country_ar' => 'توفالو',
                'nationality_en' => 'Tuvaluan',
                'nationality_ar' => 'توفالي',
            ],
            228 => [
                'code' => 'UG',
                'country_en' => ' Uganda',
                'country_ar' => 'أوغندا',
                'nationality_en' => 'Ugandan',
                'nationality_ar' => 'أوغندي',
            ],
            229 => [
                'code' => 'UA',
                'country_en' => ' Ukraine',
                'country_ar' => 'أوكرانيا',
                'nationality_en' => 'Ukrainian',
                'nationality_ar' => 'أوكراني',
            ],
            230 => [
                'code' => 'AE',
                'country_en' => ' United Arab Emirates',
                'country_ar' => 'الإمارات العربية المتحدة',
                'nationality_en' => 'Emirati',
                'nationality_ar' => 'إماراتي',
            ],
            231 => [
                'code' => 'GB',
                'country_en' => ' United Kingdom',
                'country_ar' => 'المملكة المتحدة',
                'nationality_en' => 'British',
                'nationality_ar' => 'بريطاني',
            ],
            232 => [
                'code' => 'US',
                'country_en' => ' United States',
                'country_ar' => 'الولايات المتحدة',
                'nationality_en' => 'American',
                'nationality_ar' => 'أمريكي',
            ],
            233 => [
                'code' => 'UM',
                'country_en' => ' US Minor Outlying Islands',
                'country_ar' => 'قائمة الولايات والمناطق الأمريكية',
                'nationality_en' => 'US Minor Outlying Islander',
                'nationality_ar' => 'أمريكي',
            ],
            234 => [
                'code' => 'UY',
                'country_en' => ' Uruguay',
                'country_ar' => 'أورغواي',
                'nationality_en' => 'Uruguayan',
                'nationality_ar' => 'أورغواي',
            ],
            235 => [
                'code' => 'UZ',
                'country_en' => ' Uzbekistan',
                'country_ar' => 'أوزباكستان',
                'nationality_en' => 'Uzbek',
                'nationality_ar' => 'أوزباكستاني',
            ],
            236 => [
                'code' => 'VU',
                'country_en' => ' Vanuatu',
                'country_ar' => 'فانواتو',
                'nationality_en' => 'Vanuatuan',
                'nationality_ar' => 'فانواتي',
            ],
            237 => [
                'code' => 'VE',
                'country_en' => ' Venezuela',
                'country_ar' => 'فنزويلا',
                'nationality_en' => 'Venezuelan',
                'nationality_ar' => 'فنزويلي',
            ],
            238 => [
                'code' => 'VN',
                'country_en' => ' Vietnam',
                'country_ar' => 'فيتنام',
                'nationality_en' => 'Vietnamese',
                'nationality_ar' => 'فيتنامي',
            ],
            239 => [
                'code' => 'VI',
                'country_en' => ' Virgin Islands (U.S.)',
                'country_ar' => 'الجزر العذراء الأمريكي',
                'nationality_en' => 'American Virgin Islander',
                'nationality_ar' => 'أمريكي',
            ],
            240 => [
                'code' => 'VA',
                'country_en' => ' Vatican City',
                'country_ar' => 'فنزويلا',
                'nationality_en' => 'Vatican',
                'nationality_ar' => 'فاتيكاني',
            ],
            241 => [
                'code' => 'WF',
                'country_en' => ' Wallis and Futuna Islands',
                'country_ar' => 'والس وفوتونا',
                'nationality_en' => 'Wallisian/Futunan',
                'nationality_ar' => 'فوتوني',
            ],
            242 => [
                'code' => 'EH',
                'country_en' => ' Western Sahara',
                'country_ar' => 'الصحراء الغربية',
                'nationality_en' => 'Sahrawian',
                'nationality_ar' => 'صحراوي',
            ],
            243 => [
                'code' => 'YE',
                'country_en' => ' Yemen',
                'country_ar' => 'اليمن',
                'nationality_en' => 'Yemeni',
                'nationality_ar' => 'يمني',
            ],
            244 => [
                'code' => 'ZM',
                'country_en' => ' Zambia',
                'country_ar' => 'زامبيا',
                'nationality_en' => 'Zambian',
                'nationality_ar' => 'زامبياني',
            ],
            245 => [
                'code' => 'ZW',
                'country_en' => ' Zimbabwe',
                'country_ar' => 'زمبابوي',
                'nationality_en' => 'Zimbabwean',
                'nationality_ar' => 'زمبابوي',
            ],
        ];

        foreach ($list as $nationality) {
            Nationality::create([
                "code" => $nationality['code'],
                "name" => [
                    'en' => $nationality['nationality_en'],
                    'ar' => $nationality['nationality_ar'],
                ],
            ]);
        }
    }
}